// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Testing go-swagger generation
//
//  The purpose of this application is to test go-swagger in a simple GET request.
//  Schemes:
//    http
//  Host: localhost:8080
//  BasePath: /
//  Version: 0.0.1
//  License: MIT http://opensource.org/licenses/MIT
//  Contact: Daniel<danielfs.ti@gmail.com>
//
//  Consumes:
//    - text/plain
//
//  Produces:
//    - text/plain
//
// swagger:meta
package restapi
