// Code generated by go-swagger; DO NOT EDIT.

package hello

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// HelloOKCode is the HTTP code returned for type HelloOK
const HelloOKCode int = 200

/*HelloOK The hello message

swagger:response helloOK
*/
type HelloOK struct {
}

// NewHelloOK creates HelloOK with default headers values
func NewHelloOK() *HelloOK {

	return &HelloOK{}
}

// WriteResponse to the client
func (o *HelloOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
